@data_api_HostAddress = http://localhost:5283

//GET {{data_api_HostAddress}}/projects/
//GET http://localhost:5283/api/projects-collection/
//Accept: application/json

# GET https://api.github.com/repos/caitlinthaeler/portfolio_content/contents/sk8-run/thumbnail.png?ref=main
# Authorization: Bearer {{$dotenv GITHUB_TOKEN}}

GET http://localhost:5283/api/image/sk8-run/thumbnail.png?owner=caitlinthaeler&repo=portfolio_content
Authorization: Bearer {{$dotenv GITHUB_TOKEN}}

###
